import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Sample registration requests with different vehicle types
  const sampleRegistrations = [
    {
      name: 'Jean-Pierre Kouassi',
      email: 'jean.kouassi@email.com',
      phone: '+225 07 01 23 45 67',
      location: 'Abidjan, Cocody',
      vehicleType: 'Moto',
      vehicleBrand: 'Honda',
      vehicleModel: 'CG 125',
      vehicleRegNumber: 'AB 123 CD',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Marie-Claire Diop',
      email: 'marie.diop@email.com',
      phone: '+221 77 123 45 67',
      location: 'Dakar, Liberté',
      vehicleType: 'Vélo',
      vehicleBrand: 'Decathlon',
      vehicleModel: 'Riverside 500',
      vehicleRegNumber: 'V 12345',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: false,
      insuranceVerified: false,
    },
    {
      name: 'Ahmed Benali',
      email: 'ahmed.benali@email.com',
      phone: '+216 55 123 456',
      location: 'Tunis, Sfax',
      vehicleType: 'Camion',
      vehicleBrand: 'Renault',
      vehicleModel: 'Master',
      vehicleRegNumber: 'CD 4567 EF',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Fatoumata Sow',
      email: 'fatou.sow@email.com',
      phone: '+223 60 12 34 56',
      location: 'Bamako, ACI 2000',
      vehicleType: 'Voiture',
      vehicleBrand: 'Toyota',
      vehicleModel: 'Yaris',
      vehicleRegNumber: 'DK 8901 GJ',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: false,
    },
    {
      name: 'Koffi Mensah',
      email: 'koffi.mensah@email.com',
      phone: '+233 20 123 4567',
      location: 'Accra, Cantonments',
      vehicleType: 'Moto',
      vehicleBrand: 'Suzuki',
      vehicleModel: 'GN 125',
      vehicleRegNumber: 'CE 1234 KL',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Aminata Diallo',
      email: 'amina.diallo@email.com',
      phone: '+224 62 12 34 56',
      location: 'Conakry, Ratoma',
      vehicleType: 'Camion',
      vehicleBrand: 'Ford',
      vehicleModel: 'Transit',
      vehicleRegNumber: 'DF 7890 AB',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Paul Ngou',
      email: 'paul.ngou@email.com',
      phone: '+237 67 12 34 56',
      location: 'Yaoundé, Bastos',
      vehicleType: 'Voiture',
      vehicleBrand: 'Peugeot',
      vehicleModel: '206',
      vehicleRegNumber: 'EF 2345 GH',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: false,
    },
    {
      name: 'Zainabou Ibrahim',
      email: 'zainab.ibrahim@email.com',
      phone: '+234 80 123 45678',
      location: 'Lagos, Ikeja',
      vehicleType: 'Bus',
      vehicleBrand: 'Toyota',
      vehicleModel: 'Hiace',
      vehicleRegNumber: 'AB 5678 CD',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Christian Eto',
      email: 'christian.eto@email.com',
      phone: '+237 66 12 34 56',
      location: 'Douala, Bonanjo',
      vehicleType: 'Moto',
      vehicleBrand: 'Yamaha',
      vehicleModel: 'DT 125',
      vehicleRegNumber: 'GH 3456 KL',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Nadia Cherif',
      email: 'nadia.cherif@email.com',
      phone: '+213 55 12 34 56',
      location: 'Alger, Hydra',
      vehicleType: 'Voiture',
      vehicleBrand: 'Renault',
      vehicleModel: 'Clio',
      vehicleRegNumber: 'IJ 1234 KL',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: false,
    },
    {
      name: 'Ousmane Traoré',
      email: 'ousmane.traore@email.com',
      phone: '+225 07 98 76 54 32',
      location: 'Abidjan, Yopougon',
      vehicleType: 'Tricycle',
      vehicleBrand: 'Bajaj',
      vehicleModel: 'RE',
      vehicleRegNumber: 'AB 999 XY',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Sophie Martin',
      email: 'sophie.martin@email.com',
      phone: '+33 6 12 34 56 78',
      location: 'Paris, 15e',
      vehicleType: 'Vélo',
      vehicleBrand: 'Trek',
      vehicleModel: 'FX 3',
      vehicleRegNumber: 'V 54321',
      status: 'PENDING',
      idCardVerified: false,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Ibrahim Hassan',
      email: 'ibrahim.hassan@email.com',
      phone: '+212 6 12 34 56 78',
      location: 'Casablanca, Anfa',
      vehicleType: 'Voiture',
      vehicleBrand: 'Dacia',
      vehicleModel: 'Duster',
      vehicleRegNumber: 'CE 5555 EF',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: true,
    },
    {
      name: 'Lisa Müller',
      email: 'lisa.mueller@email.com',
      phone: '+49 30 12 34 56 78',
      location: 'Berlin, Charlottenburg',
      vehicleType: 'Camion',
      vehicleBrand: 'Mercedes',
      vehicleModel: 'Sprinter',
      vehicleRegNumber: 'B 1234 MC',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: false,
      insuranceVerified: true,
    },
    {
      name: 'Marco Rossi',
      email: 'marco.rossi@email.com',
      phone: '+39 06 12 34 56 78',
      location: 'Rome, Testaccio',
      vehicleType: 'Moto',
      vehicleBrand: 'Piaggio',
      vehicleModel: 'Beverly',
      vehicleRegNumber: 'RM 4321 MR',
      status: 'PENDING',
      idCardVerified: true,
      vehicleRegVerified: true,
      insuranceVerified: false,
    },
  ]

  console.log('Creating sample registration requests...')

  for (const registration of sampleRegistrations) {
    await prisma.registrationRequest.create({
      data: registration,
    })
    console.log(`Created registration for ${registration.name} with ${registration.vehicleBrand} ${registration.vehicleModel}`)
  }

  console.log('✓ Sample data created successfully!')
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
